[".local/bin/oh-my-posh"]
  type = "file"
  url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-{{ .chezmoi.os }}-amd64"
  refreshPeriod = "168h"
  executable = true
  private = true
[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/tmaegel/nvim_config.git"
  refreshPeriod = "24h"
[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm"
  refreshPeriod = "168h"
[".local/bin/eza"]
  type = "archive-file"
  url = "https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-{{ .chezmoi.os }}-gnu.tar.gz"
  refreshPeriod = "168h"
  path = "eza"
  stripComponents = 1
  executable = true
  private = true
[".local/share/bash-completion/completions/fzf/fzf-bash-completion.sh"]
  type = "file"
  url = "https://raw.githubusercontent.com/lincheney/fzf-tab-completion/refs/heads/master/bash/fzf-bash-completion.sh"
  refreshPeriod = "168h"
  executable = false
  private = true